name: Hackademy-Az-TF--CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tf-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0
          #cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
