name: Hackademy-Az-TF--CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Hackademy-Az-TF--CI]
    types:
      - completed  

jobs:
  tf-plan-apply:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
        run: terraform plan --out=tfplan

      - name: Terraform Apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
        run: terraform apply tfplan
