name: Hackademy-Az-App--CD

on:
  #  push:
  #    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/sql-action@v1
        with:
          server-name: "hackademysql0x008"
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          project-file: "./App/PartsUnlimited.Database/PartsUnlimited.Database.sqlproj"
          build-arguments: "-c Release" # Optional arguments passed to dotnet build
          arguments: "/p:DropObjectsNotInSource=true" # Optional parameters for SqlPackage Publish
