name: Hackademy-Az-TF--CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tf-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        #with:
        # terraform_version: 0.13.0
        # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: "f0ac3453-93b5-494b-a32e-7c12593681ca"
          ARM_CLIENT_SECRET: "7tQCDoSyZ-6ee2yFhBHKL7l~3NfrlaCJ-e"
          ARM_SUBSCRIPTION_ID: "18f4adfb-c29c-4cf1-8507-0a0bfef5cceb"
          ARM_TENANT_ID: "f9aee559-f927-489a-8bc4-7812e1d31a4d"
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          ARM_CLIENT_ID: "f0ac3453-93b5-494b-a32e-7c12593681ca"
          ARM_CLIENT_SECRET: "7tQCDoSyZ-6ee2yFhBHKL7l~3NfrlaCJ-e"
          ARM_SUBSCRIPTION_ID: "18f4adfb-c29c-4cf1-8507-0a0bfef5cceb"
          ARM_TENANT_ID: "f9aee559-f927-489a-8bc4-7812e1d31a4d"
        run: terraform plan
