name: Hackademy-Az-TF--CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  tf-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
